# Trigger redeploy on 2025-10-26
name: Deploy NRGiTune Website + Apps

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositÃ³rio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Preparar artefactos
      - name: Copy Website and OpenUI5 App
        run: |
          # Copiar site para raiz
          mkdir -p artifact
          cp -r website/* artifact/

          # Copiar PowerMatch app para subpasta
          # cp -r apps/powermatch-app/* artifact/powermatch-app/
          # mkdir -p artifact
          #mkdir -p artifact/powermatch-app/webapp
          #rsync -av apps/powermatch-app/ artifact/powermatch-app/

          # Copiar PWRMatch app para subpasta
          mkdir -p artifact/pwrmatch-app/webapp
          rsync -av apps/pwrmatch-app/ artifact/pwrmatch-app/

      # 4. Criar ficheiro CNAME para GitHub Pages
      - name: Add CNAME file
        run: echo "nrgitune.pt" > artifact/CNAME

      # 5. Fazer upload do artefacto
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact

      # 6. Deploy para GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
